# Generated by Django 5.1.1 on 2024-12-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_packet_short_name_alter_packet_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='uuids',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
    ]
