# Generated by Django 5.1.1 on 2024-11-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_registy_registry_packet_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='oui',
        ),
        migrations.AddField(
            model_name='packet',
            name='long_name',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packet',
            name='oui',
            field=models.TextField(default='Cannon Unkown'),
            preserve_default=False,
        ),
    ]
