# Generated by Django 5.1.1 on 2024-10-31 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_device_rename_username_user_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packet',
            old_name='mac_address',
            new_name='advertising_address',
        ),
        migrations.RenameField(
            model_name='packet',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='packet',
            old_name='timestamp',
            new_name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='packet',
            name='mac_frequencey',
        ),
        migrations.AddField(
            model_name='packet',
            name='channel_index',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packet',
            name='counter',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packet',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='client.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packet',
            name='malicious',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packet',
            name='power_level',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packet',
            name='protocol_version',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packet',
            name='rssi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='oui',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
