# Generated by Django 5.1.1 on 2024-11-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_device_name_remove_device_oui_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='disk_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
