# Generated by Django 5.1.1 on 2024-11-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_registy_user_delete_user'),
        ('client', '0004_heartbeat_disk_info'),
    ]

    operations = [
    ]
