# Generated by Django 5.1.1 on 2024-11-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_registy_registry_remove_device_name_and_more'),
        ('client', '0005_merge_20241122_0218'),
    ]

    operations = [
    ]
