# Generated by Django 5.1.1 on 2024-11-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_merge_20241123_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('user_password', models.TextField()),
            ],
        ),
    ]
